package com.mycompany.caassignment;
// Generated 13-Mar-2016 10:29:48 by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String email;
     private byte[] password;
     private int isadmin;

    public Users() {
    }

    public Users(String email, byte[] password, int isadmin) {
       this.email = email;
       this.password = password;
       this.isadmin = isadmin;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public byte[] getPassword() {
        return this.password;
    }
    
    public void setPassword(byte[] password) {
        this.password = password;
    }
    public int getIsadmin() {
        return this.isadmin;
    }
    
    public void setIsadmin(int isadmin) {
        this.isadmin = isadmin;
    }




}


